spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 1f4beacd-b7aa-49b2-aaa1-b8525cb257e0
        credential:
          client-id: 5ae4df3e-a3ca-4bbd-a330-a52feb8bbbf0
          client-secret: ihE8Q~WVY~U5ais~-Axh-RG0CWRKkBUWaBNu8boL
        
     